name: Feature Request / Verbesserungsvorschlag
description: Request a new feature here. / Schlage eine Verbesserung vor.
title: "[Feature Request]: "
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to give us your feedback! / Vielen Dank, dass du die Zeit nimmst uns Feedback zu geben!  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your request. / Bitte beschreibe deine Anforderung.
      placeholder: What are your ideas? / Was sind deine Ideen?
    validations:
      required: true
